---
- name: Configure host
  hosts: all
  become: true

  vars_files:
    - default.config.yml


  tasks:

    - import_tasks: tasks/apps.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/fzf.yml
