---
- name: Configure host
  hosts: all
  become: true

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: update apt repo 
      apt:
        update_cache: true
        cache_valid_time: 86400 # 1 day


  tasks:

    - import_tasks: tasks/apps.yml
    - import_tasks: tasks/stow.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/fzf.yml
