---
- name: fetch fzf from github
  become: false
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: $HOME/fzf
    version: HEAD # latest

- name: check for fzf bin
  become: false
  stat:
    path: $HOME/fzf/bin/fzf
  register: fzf_result

- name: Run install script
  become: false
  shell: $HOME/fzf/install --key-bindings --completion --update-rc
  when: not fzf_result.stat.exists
