---
- name: remove vim
  apt:
    name: vim
    state: absent

- name: Add neovim ppa 
  apt_repository: 
    repo: ppa:neovim-ppa/stable
    state: present

- name: Install neovim from ppa
  apt: 
    name: neovim
    state: present

      # - name: instal vim plug
      #   become: false
      #   command: |
      #     curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      #     https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: create nvim directory
  become: false
  file: 
    path: $HOME/.config/nvim
    state: directory

- name: Check if init config is a link
  become: false
  stat:
    path: $HOME/.config/nvim/init.vim
  register: vim_config

- name: stow nvim
  become: false
  shell: |
    cd $HOME/.dotfiles
    stow nvim
  when: not vim_config.stat.exists
