---
- name: Install zsh
  apt:
    name: zsh

- name: Check if zsh is the default shell
  shell: cat /etc/passwd | grep vagrant
  register: current_shell
  changed_when: false

- debug:
    var: current_shell

- name: Make zsh the default shell
  shell: |
    chsh -s $(which zsh) vagrant
    touch .zsh
  when: '"/usr/bin/zsh" not in current_shell.stdout'

- name: check for zap binaries
  become: false
  command: cat $HOME/.local/share/zap/zap.zsh
  register: zap_result
  ignore_errors: true
  changed_when: false

- name: Install zap
  become: false
  shell: zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh) --branch release-v1
  args:
    executable: /usr/bin/zsh
  when: zap_result is failed

- name: Backup zshrc
  become: false
  copy:
    src: $HOME/.zshrc
    dest: $HOME/.zshrc.BAK
    remote_src: true
