---
- name: Install zsh
  apt:
    name: zsh

- name: Make zsh the default shell
  shell: |
    chsh -s $(which zsh) vagrant
    touch .zsh

- name: Install zap
  become: false
  shell: zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh) --branch release-v1
  args:
    executable: /usr/bin/zsh
    
