---
- name: Install zsh
  apt:
    name: zsh

- name: Check if zsh is the default shell
  become: false
  shell: cat /etc/passwd | grep $HOME
  register: current_shell
  changed_when: false

- name: Make zsh the default shell
  shell: |
    chsh -s $(which zsh) $HOME
    touch .zsh
  when: '"/usr/bin/zsh" not in current_shell.stdout'

- name: check for zap binaries
  become: false
  stat:
    path: $HOME/.local/share/zap/zap.zsh
  register: zap_bin

- name: Install zap
  become: false
  shell: zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh) --branch release-v1
  args:
    executable: /usr/bin/zsh
  when: not zap_bin.stat.exists

- name: Check if zshrc is a link file
  become: false
  stat:
    path: $HOME/.zshrc
  register: zshrc_config

- name: Backup zshrc
  become: false
  copy:
    src: $HOME/.zshrc
    dest: $HOME/.zshrc.BAK
    remote_src: true
  when: not zshrc_config.stat.islnk

- name: Delete zshrc config
  become: false
  file:
    path: $HOME/.zshrc
    state: absent
  when: not zshrc_config.stat.islnk

- name: stow zsh config
  become: false
  shell: |
    cd ~/.dotfiles
    stow zsh
  when: not zshrc_config.stat.islnk
